# Generated by Django 4.2.4 on 2023-08-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("icecreamapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="icecream",
            name="image",
            field=models.ImageField(default="exit", upload_to="gallery"),
            preserve_default=False,
        ),
    ]
