# Generated by Django 4.2.4 on 2023-08-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staticprojectapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name1", models.CharField(max_length=250)),
                ("Image1", models.ImageField(upload_to="traveller")),
                ("Details", models.TextField()),
            ],
        ),
    ]
