# Generated by Django 4.2.4 on 2023-08-22 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staticprojectapp", "0002_person"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Person",
        ),
    ]
