# Generated by Django 4.2.4 on 2023-08-23 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staticprojectapp", "0004_person"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Place",
        ),
    ]
